### PR TITLE
Fix non-removal of empty models

### PR DESCRIPTION
**Pull request by Floppy**
WIP at the moment. Done some refactoring, but I can't make my test fail, so I don't think it's actually replicating the problem we see in #624

### CODE REVIEW

**Comment by soychicka** [comment]
Curious, before this gets merged in, ...  has anyone else had a problem with models being spuriously deleted on scan?  I had all my readable files deleted twice, leaving blender and usdzs behind... 

IDK if that's a problem anyone else has, but auto-deleting empty model references could prevent others from noticing/identifying the issue.  

I haven't poked in depth as to the root cause, just disabled the deletion callback to keep it from happening again.  I also have the model files stored on a different system than the docker container, so if connectivity is lost between systems, would that cause models and tags to be wiped from my db?.

From a UX perspective, it would be better to still show SOMEWHERE empty models somewhere - rather than deleting, moving folders to an empty model graveyard directory, or at minimum displaying all auto-deletion activity in a log at admin level, if it isn't already.

**Comment by Floppy** [comment]
@soychicka that's a fair point, yes, missing files would cause them to be removed from the database, and your point about network filesystems is a really good one that I hadn't thought about. Maybe there's a better way that I should reconsider.

**Comment by Floppy** [comment]
Also, when you say "models being deleted", do you mean the actual files on disk? That's worrying, if so...

**Comment by Floppy** [comment]
@soychicka after you comment I've abandoned this approach completely, and replaced it with "problems" in #860, which flag missing files to the user rather than automatically trying to clean up. Thank you :)

**Comment by soychicka** [comment]
> @soychicka after your comment I've abandoned this approach completely, and replaced it with "problems" in #860, which flag missing files to the user rather than automatically trying to clean up. Thank you :)

No problem - I have some other ideas that I'd love to bounce off you outside the public eye - I've found you on other networks if you want to chat.  Looks like we have a lot more in common than just 3d and Ruby geekery ;)

**Comment by Floppy** [comment]
Nice one! Happy to chat on Mastodon, or on Matrix. :)

**Pull request closed without merging**
