### PR TITLE
Adds the ability to add and remove tags

### PR DESCRIPTION
**Pull request by mattpage**
This adds the ability to add and remove tags for a model.

Screen Shot 2022-04-18 at 8 13 22 AM

### CODE REVIEW

**Comment by Floppy** [comment]
Oooh, this will be amazing. Tags have been purely an auto-generated thing so far, and I've wanted to add manual control for them for ages. Excited :)

**Comment by mattpage** [comment]
> Oooh, this will be amazing. Tags have been purely an auto-generated thing so far, and I've wanted to add manual control for them for ages. Excited :)

@floppy - Any thoughts on how tags should be added?
Currently this will render all the assigned checkboxes and provide for easy removal, but adding a new tag is not supported. 

If I made this a dropdown, you could potentially select from existing tags that were unchecked, but I think this might get out of hand pretty quick, plus adding a whole new tag would still be an issue. Or I could add a button for adding a new tag that submits a form.

Here's a hacked together screenshot of ideas

Screen Shot 2022-04-18 at 8 13 22 AM

**Comment by Floppy** [comment]
In the past I've used some javascript, maybe something like select2, combined with the auto-creation of new tags with acts_as_taggable_on when you save a model. But that's well out of date, and I'm not sure what the current state of the art is. 

Looks like selectize.js is a good one (https://selectize.dev/demos/2016/01/02/tagging/); https://stackoverflow.com/questions/39921381/adding-a-tag-if-it-doesnt-exist-in-rails-chosen-rails#39922922 talks about using it. Looks like if you just tell it to create a comma-separated string, then save that as the tag list, acts_as_taggable_on will deal with the rest?

**Comment by mattpage** [comment]
@Floppy - I updated this to use selectize. I still need to add some tests for updating tags, but how does this look to you?

Screen Shot 2022-04-19 at 5 08 55 PM

**Comment by Floppy** [comment]
That, my friend, looks awesome. ❤️

**Comment by mattpage** [comment]
@Floppy - I think this is ready for your review

**Review by Floppy — APPROVED** [review]

**Pull request merged**
